### ISSUE TITLE
StreamReaderとの挙動の差について

### ISSUE THREAD

**Issue by inaenomaki** [kkato233/Nkf.Net#7]
はじめまして。
こちらのライブラリを使用させていただいている いなえ と申します。
導入がNuGetで可能になっていたため、簡易に欲しい機能を実現できたので重宝しております、ありがとうございます。

気になる点があったので勝手ながらIssueを作成させていただきました。
要点としては「StreamReaderとNkfTextReeaderの差分について」です。

`NkfTextReader` は `System.IO.TextReader` を実装していますが、同様にこれを実装している `StreamReader` と挙動に差があることに気付きました。
挙動に差がある例としては
```
string text = null;
using (var sr = new Nkf.Net.NkfTextReader(fileName))
{
    text = sr.ReadToEnd();
}
```
という処理を書いた場合です。具体的には以下になります。

|     |                                                | StreamReader | NkfTextReader    | 
| --- | ---------------------------------------------- | ------------ | ---------------- | 
| 1   | 改行コードがLFのファイルを開いた際の改行コード | 全てLFのまま     | 全てCRLFに変換される | 
| 2   | ファイル末尾の改行コード(LF, CRLFともに)       | そのまま     | 削除される       | 

1に関しては、処理を拝見したところ、`ReadToEnd()` 内で `ReadLine()` して各行を取得した後、`string.Join("\r\n", line.ToArray());` とCRLFをくっつける形で全体を構築している為、LFが改行コードのファイルでも改行コードがCRLFになっているのかと思いました。

また、2に関しても同様の箇所で各行の間にCRLFをくっつけているがために末尾の改行コードが落ちてしまっているのが原因かと思っています。

これらに関しては想定挙動でしょうか？

**Comment by kkato233** [comment]
>想定挙動でしょうか？

`NkfTextReader`  は お手軽に `StreamReader` の 代わりに使える事を目指して
ファイルに含まれる日本語文字列を取り出すことを目的に作りました。

ReadToEnd における 改行コードについては意識していませんでした。

改行コードを気にされているのは 日本語に変換した結果を ファイルに保存して
次の処理で利用するからですか？

もし、であれば `WrapNkf.FileConvert2` を使ってみてはいかがでしょうか？

##### nkf の機能を直接利用してファイル変換する

``` C#
// ファイルをUTF8 変換（入力ファイルのエンコードは未指定）
Nkf.Net.WrapNkf.SetNkfOption("-w");	// UTF-8
Nkf.Net.WrapNkf.FileConvert2(inFile, outFile);
```

**Comment by kkato233** [comment]
または 下記のように ReadToEnd 関数をオーバーライドした 拡張クラスを利用する方法もあります。

``` C#
class NkfTextReaderEx : Nkf.Net.NkfTextReader {

    public NkfTextReaderEx(string fileName) : base(fileName) {
    }
    public NkfTextReaderEx(Stream fs) : base(fs) {
    }

    public override string ReadToEnd()
    {
        var sb = new System.Text.StringBuilder();
        string s;
        while ((s = ReadLine()) != null)
        {
            sb.AppendLine(s);
        }

        return sb.ToString();
    }
}
```

**Comment by kkato233** [comment]
または `Nkf.Net.WrapNkf.NkfConvert` を直接呼び出して

``` C#
string ReadFileContents(string fileName)
{
    using (Stream st = new System.IO.FileStream(fileName,
            System.IO.FileMode.Open, System.IO.FileAccess.Read)) {

        byte[] data = new byte[st.Length];
        int read_n = st.Read(data, 0, data.Length);

        string sData = Nkf.Net.WrapNkf.NkfConvert(data, 0, read_n);

        return sData;
    };
}
```

という方法もあります。

**Comment by inaenomaki** [comment]
返信が遅くなり申し訳ありません。

>指摘 2 の 最後の行末の CRLF が 消える現象は バグFIXとして修正する候補に入れておきます。
指摘 1 については ReadToEnd が ReadLine ベースで作っているため、現状の ReadLine を使う限り
　　　対応がむつかしく、現時点での仕様ということになります。

ご確認ありがとうございます。承知しました。

>改行コードを気にされているのは 日本語に変換した結果を ファイルに保存して
次の処理で利用するからですか？

概ね仰る通りです。様々な文字コードで保存されているファイルを(特定の変換処理をした上で)UTF-8で保存しなおす、というのが要件になります。
元々UTF-8のファイルを上記処理にかけた場合にはファイル差分がない想定だったのですが、実際やってみると改行コード周りで差分が出ていたのでこちらでお聞きしたという経緯になります。

ご提案いただいた方法で要件を満たせそうなので試してみます。
ご親切に対応いただきありがとうございました。
